/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 maxwell.gltf -k -keepmeshes 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/maxwell.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" userData={{ name: 'Armature' }}>
          <primitive object={nodes.Base} />
          <primitive object={nodes.HeadIK} />
          <primitive object={nodes.ArmIKLeft} />
          <primitive object={nodes.ArmIKRight} />
          <primitive object={nodes.TailIK} />
          <primitive object={nodes.LegIKLeft} />
          <primitive object={nodes.LegIKRight} />
          <group name="Body" userData={{ name: 'Body' }}>
            <skinnedMesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials.Tail} skeleton={nodes.Body_1.skeleton} />
            <skinnedMesh name="Body_2" geometry={nodes.Body_2.geometry} material={materials.Body} skeleton={nodes.Body_2.skeleton} />
            <skinnedMesh name="Body_3" geometry={nodes.Body_3.geometry} material={materials.Mouth} skeleton={nodes.Body_3.skeleton} />
            <skinnedMesh name="Body_4" geometry={nodes.Body_4.geometry} material={materials.Belly} skeleton={nodes.Body_4.skeleton} />
          </group>
          <skinnedMesh name="Bowtie" geometry={nodes.Bowtie.geometry} material={materials.Bowtie} skeleton={nodes.Bowtie.skeleton} userData={{ name: 'Bowtie' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/maxwell.gltf')
