/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 maxwell_the_beaver_final.glb --transform -keepmeshes 
Files: maxwell_the_beaver_final.glb [410.16KB] > maxwell_the_beaver_final-transformed.glb [347.99KB] (15%)
*/

import React, { useState, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export default function Maxwell(props) {
  const [currentAnimation, setCurrentAnimation] = useState('Greet')
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/maxwell_the_beaver_final-transformed.glb')
  const { actions, mixer } = useAnimations(animations, group)

  console.log(nodes, animations, actions)
  console.log(nodes.Pencil)
  console.log(nodes.Paper)

  useEffect(() => {
    if (currentAnimation === 'Greet') {
      nodes.Pencil.visible = false;
      nodes.Paper.visible = false;
      actions[currentAnimation].reset()
      actions[currentAnimation].setLoop(THREE.LoopOnce);
      actions[currentAnimation].play()
      mixer.addEventListener('finished', () => {
        actions[currentAnimation].fadeOut(0.5);
        actions['Idle'].reset().fadeIn(0.5).play();
      })
    } else if (currentAnimation === 'Idle') {
      nodes.Pencil.visible = false;
      nodes.Paper.visible = false;
    } else if (currentAnimation === 'Reading') {
      nodes.Pencil.visible = false;
      nodes.Paper.visible = true;
    } else if (currentAnimation === 'Writing') {
      nodes.Pencil.visible = true;
      nodes.Paper.visible = true;
    }

    actions[currentAnimation].reset().fadeIn(0.5).play();
    return () => {
      actions[currentAnimation].fadeOut(0.5);
    }
  }, [currentAnimation]);

  return (
    <group castShadow ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" userData={{ name: 'Armature' }}>
          <primitive object={nodes.Base} />
          <primitive object={nodes.HeadIK} />
          <primitive object={nodes.ArmIKLeft} />
          <primitive object={nodes.ArmIKRight} />
          <primitive object={nodes.TailIK} />
          <primitive object={nodes.LegIKLeft} />
          <primitive object={nodes.LegIKRight} />
        </group>
        <group name="Body" userData={{ name: 'Body' }}>
          <skinnedMesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Body_1.skeleton} />
          <skinnedMesh name="Body_2" geometry={nodes.Body_2.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Body_2.skeleton} />
          <skinnedMesh name="Body_3" geometry={nodes.Body_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Body_3.skeleton} />
          <skinnedMesh name="Body_4" geometry={nodes.Body_4.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Body_4.skeleton} />
        </group>
        <skinnedMesh name="Bowtie" geometry={nodes.Bowtie.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Bowtie.skeleton} userData={{ name: 'Bowtie' }} />
        <mesh geometry={nodes.Pencil.geometry} material={materials.PaletteMaterial003} userData={{ name: 'Pencil' }} />
        <mesh geometry={nodes.Paper.geometry} material={materials.PaletteMaterial001} userData={{ name: 'Paper' }} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/maxwell_the_beaver_final-transformed.glb')
